"""empty message

Revision ID: 1643a41b8d16
Revises: None
Create Date: 2015-08-07 12:33:26.595145

"""

# revision identifiers, used by Alembic.
revision = '1643a41b8d16'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
