"""empty message

Revision ID: 21bb1980d045
Revises: 1643a41b8d16
Create Date: 2015-08-12 09:26:40.850832

"""

# revision identifiers, used by Alembic.
revision = '21bb1980d045'
down_revision = '1643a41b8d16'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass

    #op.drop_column(u'captures', 'returns')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'captures', sa.Column('returns', sa.TEXT(), nullable=True))
    op.drop_table('collector')
    ### end Alembic commands ###
