"""empty message

Revision ID: 2334b4d3b7be
Revises: 4c6d24c7bea1
Create Date: 2015-08-12 10:52:15.909147

"""

# revision identifiers, used by Alembic.
revision = '2334b4d3b7be'
down_revision = '4c6d24c7bea1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('captures', 'returns')
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generic_collector', 'url')
    op.drop_column('generic_collector', 'referrer')
    op.drop_column('generic_collector', 'pub_date')
    op.add_column('captures', sa.Column('returns', sa.TEXT(), nullable=True))
    ### end Alembic commands ###
