"""empty message

Revision ID: 30550137e571
Revises: 16a92c216f4c
Create Date: 2015-08-13 17:45:26.239018

"""

# revision identifiers, used by Alembic.
revision = '30550137e571'
down_revision = '16a92c216f4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('captures', 'returns')
    op.add_column('generic_collector', sa.Column('payload', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'generic_collector', type_='foreignkey')
    op.create_foreign_key(None, 'generic_collector', 'payloads', ['payload'], ['id'])
    op.drop_column('generic_collector', 'payload_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generic_collector', sa.Column('payload_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'generic_collector', type_='foreignkey')
    op.create_foreign_key(None, 'generic_collector', 'payloads', ['payload_id'], ['id'])
    op.drop_column('generic_collector', 'payload')
    op.add_column('captures', sa.Column('returns', sa.TEXT(), nullable=True))
    ### end Alembic commands ###
